# for send email by Gmail
# GMAIL_USERNAME
# GMAIL_PASSWORD

# for seed file
# ADMIN_1_USERNAME
# ADMIN_1_EMAIL
# ADMIN_1_PASSWORD

# for seed file
# ADMIN_2_USERNAME
# ADMIN_2_EMAIL
# ADMIN_2_PASSWORD