# for send email by Gmail
#   GMAIL_USERNAME
#   GMAIL_PASSWORD

# for seed file
#   ADMIN_1_USERNAME
#   ADMIN_1_EMAIL
#   ADMIN_1_PASSWORD

# for seed file
#   ADMIN_2_USERNAME
#   ADMIN_2_EMAIL
#   ADMIN_2_PASSWORD

# for seed file
#   BACKUP_USERNAME
#   BACKUP_EMAIL
#   BACKUP_PASSWORD

# for USPS api
#   USPS_USER_ID
#   HOME_ZIP_CODE

# for Stripe
#   PUBLISHABLE_KEY
#   SECRET_KEY